name: Github Actions, CloudType CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql_charset: 'utf8'
          mysql_version: '8.0.33'
          mysql_database: 'shop'
          mysql_root_password: 'admin'

      - name: Run unit tests
        run: ./gradlew clean test --exclude-task test

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: beomsu_1221/selectshop
          stage: main
          yaml: |
            name: selectshop
            app: java@17
            options:
              ports: 8080
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
